-- 아이스크림 프로 홈페이지 Supabase 스키마 + 초기 데이터
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 RUN 하세요.

-- 1) 테이블 ---------------------------------------------------
create table if not exists categories (
  key   text primary key,
  label text not null,
  icon  text,
  sort  int default 0
);

create table if not exists courses (
  id            bigint primary key,
  title         text not null,
  credit        text,
  category      text references categories(key),
  category_name text,
  price         bigint default 0,
  status        text default 'open',
  url           text
);

create table if not exists inquiries (
  id         bigint generated by default as identity primary key,
  org        text,
  region     text,
  phone      text,
  message    text,
  status     text default 'new',
  created_at timestamptz default now()
);
-- 2) 보안(RLS): 카탈로그는 공개 읽기, 문의는 등록만 허용 ----------
alter table categories enable row level security;
alter table courses    enable row level security;
alter table inquiries  enable row level security;

create policy "read categories" on categories for select to anon using (true);
create policy "read courses"    on courses    for select to anon using (true);
create policy "insert inquiry"  on inquiries  for insert to anon with check (true);
-- 3) 초기 데이터(seed) --------------------------------------
insert into categories (key,label,icon,sort) values ('digital','디지털역량','🤖',1) on conflict (key) do nothing;
insert into categories (key,label,icon,sort) values ('humanities','인문소양','📖',2) on conflict (key) do nothing;
insert into categories (key,label,icon,sort) values ('teaching','교수학습','📚',3) on conflict (key) do nothing;
insert into categories (key,label,icon,sort) values ('language','어학','🗣️',4) on conflict (key) do nothing;
insert into categories (key,label,icon,sort) values ('classroom','학급경영','🏫',5) on conflict (key) do nothing;

insert into courses (id,title,credit,category,category_name,price,status,url) values (7349,'깊이 있는 학습 & 학습 주도성 Up!  AI 시대를 이끄는 질문의 힘','2','teaching','교수학습',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7349') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7357,'부모 인문학 클래스: 엄빠의 질문','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7357') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3058,'아이들이 먼저 집중하는 시간! 교사도 따라하는 교실 밀착 마술','X','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3058') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7334,'현장에서 바로 쓰는 교직실무 가이드 A to Z','4','classroom','학급경영',140000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7334') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7346,'걱정없이 떠나는 여행 일본어 무작정 따라하기','1','language','어학',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7346') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7347,'현실 월급쟁이의 재테크 1년 로드맵','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7347') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3057,'딱 10분! AI로 뚝딱 만드는 작사작곡','X','digital','디지털역량',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3057') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7325,'우영쌤의 쉽게 준비하고 바로 적용하는 과학 실험','1','teaching','교수학습',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7325') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7354,'최소한의 세금공부','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7354') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7352,'1등급은 다르다! 수상자들의 디지털교육 연구대회 필승 전략','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7352') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7350,'선생님을 바꾸는 크로스핏! 살은 빼고 건강은 더하기','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7350') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7339,'하루 20분, 몸이 달라지는 필라테스의 정석','2','humanities','인문소양',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7339') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3051,'AI 에이전트 핵심만 쏙쏙 배우기 - 입문에서 실전까지, 업무 비서를 넘어선 초지능 에이전트','X','digital','디지털역량',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3051') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3053,'수업에 매직 한 스푼! 교실에서 함께하는 카드 마술','X','teaching','교수학습',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3053') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3050,'AI 이미지 생성의 대세, 나노바나나로 초격차 디자인 마스터하기','X','digital','디지털역량',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3050') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3052,'AI로 들여다보는 역사의 라이벌 - 조선편','X','humanities','인문소양',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3052') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7337,'학교자율시간, 수업으로 바로 쓰다','1','classroom','학급경영',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7337') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3056,'Google 실무 마스터 - Gemini, NotebookLM, Antigravity','X','digital','디지털역량',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3056') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7336,'블록코딩으로 배우는 AI, AICE Future 완벽대비','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7336') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7348,'김창옥의 나의 힐링 아지트','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7348') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (1248,'학교 업무 자동화를 위한 구글시트 첫걸음','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=1248') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7335,'AI 통합 플랫폼, 구글 AI 스튜디오 완전정복 - 문서, 이미지, 영상 제작부터 바이브코딩까지 한 번에!','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7335') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7328,'공부천재 서경석의 한국사능력검정시험 심화','4','humanities','인문소양',140000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7328') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7338,'꼭 알아야 할 최소한의 건강 지식','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7338') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7329,'공부천재 서경석의 한국사능력검정시험 (심화)-상','2','humanities','인문소양',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7329') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7330,'공부천재 서경석의 한국사능력검정시험 (심화)-하','2','humanities','인문소양',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7330') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3055,'교사의 시간을 돌려주는 AI: issamGPT 활용법','X','digital','디지털역량',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3055') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7320,'교원 업무 혁신! ChatGPT로 끝내는 엑셀 자동화','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7320') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7342,'영어회화 핵심패턴 233 - 핵심패턴편','2','language','어학',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7342') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7343,'영어회화 핵심패턴 233 - 기본패턴편','2','language','어학',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7343') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7344,'놀이로 시작하는 사회정서교육','1','teaching','교수학습',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7344') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3049,'우리반 AI 수업비서 알공 활용 노하우','X','digital','디지털역량',30000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3049') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3054,'RUN for U, 달리기 입문 클래스(러닝의 시작)','X','humanities','인문소양',35000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3054') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7326,'큰별쌤 최태성의 한국사신문','2','humanities','인문소양',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7326') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7321,'미니학습지 유럽여행회화 미니패스-스페인어, 이탈리아어, 프랑스어, 독일어','1','language','어학',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7321') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (1246,'살찌지 않는 최적의 식사전략, 박용우의 진짜 다이어트','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=1246') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7340,'유성호 법의학자 생존 교양 지식, 시체는 거짓말 하지 않는다','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7340') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7331,'교사별 과정중심평가에 색을 입히다','1','teaching','교수학습',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7331') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7318,'역사 스토리텔러 두선생의 딱 보면 보이는 세계사','1','humanities','인문소양',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7318') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7333,'Google & Gemini로 수업을 바꾸는 교사들의 시크릿','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7333') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7327,'리얼 시뮬레이션 여행영어','2','language','어학',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7327') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (7332,'생활밀착형 에피소드 30개로 보는 법률상식','2','humanities','인문소양',85000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=7332') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (5077,'핵심 포인트로 영어 수업 레벨업하기','X','teaching','교수학습',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=5077') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (1247,'생성형 AI 활용, 유아 교사를 위한 디지털 업무 경감','1','digital','디지털역량',50000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=1247') on conflict (id) do nothing;
insert into courses (id,title,credit,category,category_name,price,status,url) values (3047,'제로에서 시작하는 샌드아트','X','humanities','인문소양',25000,'open','https://teacher.i-scream.co.kr/course/crs/creditView.do?crsCode=3047') on conflict (id) do nothing;
